import tokens from "@digital-go-jp/design-tokens";

const colors = {
  white: { value: tokens.Color.Neutral.White.value },
  black: { value: tokens.Color.Neutral.Black.value },
  sea: {
    50: { value: tokens.Color.Primitive.Sea[50].value },
    100: { value: tokens.Color.Primitive.Sea[100].value },
    200: { value: tokens.Color.Primitive.Sea[200].value },
    300: { value: tokens.Color.Primitive.Sea[300].value },
    400: { value: tokens.Color.Primitive.Sea[400].value },
    500: { value: tokens.Color.Primitive.Sea[500].value },
    600: { value: tokens.Color.Primitive.Sea[600].value },
    700: { value: tokens.Color.Primitive.Sea[700].value },
    800: { value: tokens.Color.Primitive.Sea[800].value },
    900: { value: tokens.Color.Primitive.Sea[900].value },
    1000: { value: tokens.Color.Primitive.Sea[1000].value },
    1100: { value: tokens.Color.Primitive.Sea[1100].value },
    1200: { value: tokens.Color.Primitive.Sea[1200].value },
  },
  sumi: {
    50: { value: tokens.Color.Primitive.Sumi[50].value },
    100: { value: tokens.Color.Primitive.Sumi[100].value },
    200: { value: tokens.Color.Primitive.Sumi[200].value },
    300: { value: tokens.Color.Primitive.Sumi[300].value },
    400: { value: tokens.Color.Primitive.Sumi[400].value },
    500: { value: tokens.Color.Primitive.Sumi[500].value },
    600: { value: tokens.Color.Primitive.Sumi[600].value },
    700: { value: tokens.Color.Primitive.Sumi[700].value },
    800: { value: tokens.Color.Primitive.Sumi[800].value },
    900: { value: tokens.Color.Primitive.Sumi[900].value },
    1000: { value: tokens.Color.Primitive.Sumi[1000].value },
    1100: { value: tokens.Color.Primitive.Sumi[1100].value },
    1200: { value: tokens.Color.Primitive.Sumi[1200].value },
  },
  forest: {
    50: { value: tokens.Color.Primitive.Forest[50].value },
    100: { value: tokens.Color.Primitive.Forest[100].value },
    200: { value: tokens.Color.Primitive.Forest[200].value },
    300: { value: tokens.Color.Primitive.Forest[300].value },
    400: { value: tokens.Color.Primitive.Forest[400].value },
    500: { value: tokens.Color.Primitive.Forest[500].value },
    600: { value: tokens.Color.Primitive.Forest[600].value },
    700: { value: tokens.Color.Primitive.Forest[700].value },
    800: { value: tokens.Color.Primitive.Forest[800].value },
    900: { value: tokens.Color.Primitive.Forest[900].value },
    1000: { value: tokens.Color.Primitive.Forest[1000].value },
    1100: { value: tokens.Color.Primitive.Forest[1100].value },
    1200: { value: tokens.Color.Primitive.Forest[1200].value },
  },
  wood: {
    50: { value: tokens.Color.Primitive.Wood[50].value },
    100: { value: tokens.Color.Primitive.Wood[100].value },
    200: { value: tokens.Color.Primitive.Wood[200].value },
    300: { value: tokens.Color.Primitive.Wood[300].value },
    400: { value: tokens.Color.Primitive.Wood[400].value },
    500: { value: tokens.Color.Primitive.Wood[500].value },
    600: { value: tokens.Color.Primitive.Wood[600].value },
    700: { value: tokens.Color.Primitive.Wood[700].value },
    800: { value: tokens.Color.Primitive.Wood[800].value },
    900: { value: tokens.Color.Primitive.Wood[900].value },
    1000: { value: tokens.Color.Primitive.Wood[1000].value },
    1100: { value: tokens.Color.Primitive.Wood[1100].value },
    1200: { value: tokens.Color.Primitive.Wood[1200].value },
  },
  sun: {
    50: { value: tokens.Color.Primitive.Sun[50].value },
    100: { value: tokens.Color.Primitive.Sun[100].value },
    200: { value: tokens.Color.Primitive.Sun[200].value },
    300: { value: tokens.Color.Primitive.Sun[300].value },
    400: { value: tokens.Color.Primitive.Sun[400].value },
    500: { value: tokens.Color.Primitive.Sun[500].value },
    600: { value: tokens.Color.Primitive.Sun[600].value },
    700: { value: tokens.Color.Primitive.Sun[700].value },
    800: { value: tokens.Color.Primitive.Sun[800].value },
    900: { value: tokens.Color.Primitive.Sun[900].value },
    1000: { value: tokens.Color.Primitive.Sun[1000].value },
    1100: { value: tokens.Color.Primitive.Sun[1100].value },
    1200: { value: tokens.Color.Primitive.Sun[1200].value },
  },
  blue: {
    50: { value: tokens.Color.Primitive.Blue[50].value },
    100: { value: tokens.Color.Primitive.Blue[100].value },
    200: { value: tokens.Color.Primitive.Blue[200].value },
    300: { value: tokens.Color.Primitive.Blue[300].value },
    400: { value: tokens.Color.Primitive.Blue[400].value },
    500: { value: tokens.Color.Primitive.Blue[500].value },
    600: { value: tokens.Color.Primitive.Blue[600].value },
    700: { value: tokens.Color.Primitive.Blue[700].value },
    800: { value: tokens.Color.Primitive.Blue[800].value },
    900: { value: tokens.Color.Primitive.Blue[900].value },
    1000: { value: tokens.Color.Primitive.Blue[1000].value },
    1100: { value: tokens.Color.Primitive.Blue[1100].value },
    1200: { value: tokens.Color.Primitive.Blue[1200].value },
  },
  "light-blue": {
    50: { value: tokens.Color.Primitive.LightBlue[50].value },
    100: { value: tokens.Color.Primitive.LightBlue[100].value },
    200: { value: tokens.Color.Primitive.LightBlue[200].value },
    300: { value: tokens.Color.Primitive.LightBlue[300].value },
    400: { value: tokens.Color.Primitive.LightBlue[400].value },
    500: { value: tokens.Color.Primitive.LightBlue[500].value },
    600: { value: tokens.Color.Primitive.LightBlue[600].value },
    700: { value: tokens.Color.Primitive.LightBlue[700].value },
    800: { value: tokens.Color.Primitive.LightBlue[800].value },
    900: { value: tokens.Color.Primitive.LightBlue[900].value },
    1000: { value: tokens.Color.Primitive.LightBlue[1000].value },
    1100: { value: tokens.Color.Primitive.LightBlue[1100].value },
    1200: { value: tokens.Color.Primitive.LightBlue[1200].value },
  },
  cyan: {
    50: { value: tokens.Color.Primitive.Cyan[50].value },
    100: { value: tokens.Color.Primitive.Cyan[100].value },
    200: { value: tokens.Color.Primitive.Cyan[200].value },
    300: { value: tokens.Color.Primitive.Cyan[300].value },
    400: { value: tokens.Color.Primitive.Cyan[400].value },
    500: { value: tokens.Color.Primitive.Cyan[500].value },
    600: { value: tokens.Color.Primitive.Cyan[600].value },
    700: { value: tokens.Color.Primitive.Cyan[700].value },
    800: { value: tokens.Color.Primitive.Cyan[800].value },
    900: { value: tokens.Color.Primitive.Cyan[900].value },
    1000: { value: tokens.Color.Primitive.Cyan[1000].value },
    1100: { value: tokens.Color.Primitive.Cyan[1100].value },
    1200: { value: tokens.Color.Primitive.Cyan[1200].value },
  },
  green: {
    50: { value: tokens.Color.Primitive.Green[50].value },
    100: { value: tokens.Color.Primitive.Green[100].value },
    200: { value: tokens.Color.Primitive.Green[200].value },
    300: { value: tokens.Color.Primitive.Green[300].value },
    400: { value: tokens.Color.Primitive.Green[400].value },
    500: { value: tokens.Color.Primitive.Green[500].value },
    600: { value: tokens.Color.Primitive.Green[600].value },
    700: { value: tokens.Color.Primitive.Green[700].value },
    800: { value: tokens.Color.Primitive.Green[800].value },
    900: { value: tokens.Color.Primitive.Green[900].value },
    1000: { value: tokens.Color.Primitive.Green[1000].value },
    1100: { value: tokens.Color.Primitive.Green[1100].value },
    1200: { value: tokens.Color.Primitive.Green[1200].value },
  },
  lime: {
    50: { value: tokens.Color.Primitive.Lime[50].value },
    100: { value: tokens.Color.Primitive.Lime[100].value },
    200: { value: tokens.Color.Primitive.Lime[200].value },
    300: { value: tokens.Color.Primitive.Lime[300].value },
    400: { value: tokens.Color.Primitive.Lime[400].value },
    500: { value: tokens.Color.Primitive.Lime[500].value },
    600: { value: tokens.Color.Primitive.Lime[600].value },
    700: { value: tokens.Color.Primitive.Lime[700].value },
    800: { value: tokens.Color.Primitive.Lime[800].value },
    900: { value: tokens.Color.Primitive.Lime[900].value },
    1000: { value: tokens.Color.Primitive.Lime[1000].value },
    1100: { value: tokens.Color.Primitive.Lime[1100].value },
    1200: { value: tokens.Color.Primitive.Lime[1200].value },
  },
  yellow: {
    50: { value: tokens.Color.Primitive.Yellow[50].value },
    100: { value: tokens.Color.Primitive.Yellow[100].value },
    200: { value: tokens.Color.Primitive.Yellow[200].value },
    300: { value: tokens.Color.Primitive.Yellow[300].value },
    400: { value: tokens.Color.Primitive.Yellow[400].value },
    500: { value: tokens.Color.Primitive.Yellow[500].value },
    600: { value: tokens.Color.Primitive.Yellow[600].value },
    700: { value: tokens.Color.Primitive.Yellow[700].value },
    800: { value: tokens.Color.Primitive.Yellow[800].value },
    900: { value: tokens.Color.Primitive.Yellow[900].value },
    1000: { value: tokens.Color.Primitive.Yellow[1000].value },
    1100: { value: tokens.Color.Primitive.Yellow[1100].value },
    1200: { value: tokens.Color.Primitive.Yellow[1200].value },
  },
  orange: {
    50: { value: tokens.Color.Primitive.Orange[50].value },
    100: { value: tokens.Color.Primitive.Orange[100].value },
    200: { value: tokens.Color.Primitive.Orange[200].value },
    300: { value: tokens.Color.Primitive.Orange[300].value },
    400: { value: tokens.Color.Primitive.Orange[400].value },
    500: { value: tokens.Color.Primitive.Orange[500].value },
    600: { value: tokens.Color.Primitive.Orange[600].value },
    700: { value: tokens.Color.Primitive.Orange[700].value },
    800: { value: tokens.Color.Primitive.Orange[800].value },
    900: { value: tokens.Color.Primitive.Orange[900].value },
    1000: { value: tokens.Color.Primitive.Orange[1000].value },
    1100: { value: tokens.Color.Primitive.Orange[1100].value },
    1200: { value: tokens.Color.Primitive.Orange[1200].value },
  },
  red: {
    50: { value: tokens.Color.Primitive.Red[50].value },
    100: { value: tokens.Color.Primitive.Red[100].value },
    200: { value: tokens.Color.Primitive.Red[200].value },
    300: { value: tokens.Color.Primitive.Red[300].value },
    400: { value: tokens.Color.Primitive.Red[400].value },
    500: { value: tokens.Color.Primitive.Red[500].value },
    600: { value: tokens.Color.Primitive.Red[600].value },
    700: { value: tokens.Color.Primitive.Red[700].value },
    800: { value: tokens.Color.Primitive.Red[800].value },
    900: { value: tokens.Color.Primitive.Red[900].value },
    1000: { value: tokens.Color.Primitive.Red[1000].value },
    1100: { value: tokens.Color.Primitive.Red[1100].value },
    1200: { value: tokens.Color.Primitive.Red[1200].value },
  },
  magenta: {
    50: { value: tokens.Color.Primitive.Magenta[50].value },
    100: { value: tokens.Color.Primitive.Magenta[100].value },
    200: { value: tokens.Color.Primitive.Magenta[200].value },
    300: { value: tokens.Color.Primitive.Magenta[300].value },
    400: { value: tokens.Color.Primitive.Magenta[400].value },
    500: { value: tokens.Color.Primitive.Magenta[500].value },
    600: { value: tokens.Color.Primitive.Magenta[600].value },
    700: { value: tokens.Color.Primitive.Magenta[700].value },
    800: { value: tokens.Color.Primitive.Magenta[800].value },
    900: { value: tokens.Color.Primitive.Magenta[900].value },
    1000: { value: tokens.Color.Primitive.Magenta[1000].value },
    1100: { value: tokens.Color.Primitive.Magenta[1100].value },
    1200: { value: tokens.Color.Primitive.Magenta[1200].value },
  },
  purple: {
    50: { value: tokens.Color.Primitive.Purple[50].value },
    100: { value: tokens.Color.Primitive.Purple[100].value },
    200: { value: tokens.Color.Primitive.Purple[200].value },
    300: { value: tokens.Color.Primitive.Purple[300].value },
    400: { value: tokens.Color.Primitive.Purple[400].value },
    500: { value: tokens.Color.Primitive.Purple[500].value },
    600: { value: tokens.Color.Primitive.Purple[600].value },
    700: { value: tokens.Color.Primitive.Purple[700].value },
    800: { value: tokens.Color.Primitive.Purple[800].value },
    900: { value: tokens.Color.Primitive.Purple[900].value },
    1000: { value: tokens.Color.Primitive.Purple[1000].value },
    1100: { value: tokens.Color.Primitive.Purple[1100].value },
    1200: { value: tokens.Color.Primitive.Purple[1200].value },
  },
  "solid-grey": {
    50: { value: tokens.Color.Neutral.SolidGrey[50].value },
    100: { value: tokens.Color.Neutral.SolidGrey[100].value },
    200: { value: tokens.Color.Neutral.SolidGrey[200].value },
    300: { value: tokens.Color.Neutral.SolidGrey[300].value },
    400: { value: tokens.Color.Neutral.SolidGrey[400].value },
    420: { value: tokens.Color.Neutral.SolidGrey[420].value },
    500: { value: tokens.Color.Neutral.SolidGrey[500].value },
    536: { value: tokens.Color.Neutral.SolidGrey[536].value },
    600: { value: tokens.Color.Neutral.SolidGrey[600].value },
    700: { value: tokens.Color.Neutral.SolidGrey[700].value },
    800: { value: tokens.Color.Neutral.SolidGrey[800].value },
    900: { value: tokens.Color.Neutral.SolidGrey[900].value },
  },
  success: {
    1: {
      value: tokens.Color.Success[1].value,
      description: "成功、安全、完了などを意味するカラー",
    },
    2: {
      value: tokens.Color.Success[2].value,
      description: "成功、安全、完了などを意味するカラー",
    },
  },
  error: {
    1: {
      value: tokens.Color.Error[1].value,
      description:
        "失敗やエラーのほか、危険情報や制約条件の提示など注意喚起を意味するカラー",
    },
    2: {
      value: tokens.Color.Error[2].value,
      description:
        "失敗やエラーのほか、危険情報や制約条件の提示など注意喚起を意味するカラー",
    },
  },
  warning: {
    yellow: {
      1: {
        value: tokens.Color.Warning.Yellow[1].value,
        description: "警告や禁止事項などを意味するカラー",
      },
      2: {
        value: tokens.Color.Warning.Yellow[2].value,
        description: "警告や禁止事項などを意味するカラー",
      },
    },
    orange: {
      1: {
        value: tokens.Color.Warning.Orange[1].value,
        description: "警告や禁止事項などを意味するカラー",
      },
      2: {
        value: tokens.Color.Warning.Orange[2].value,
        description: "警告や禁止事項などを意味するカラー",
      },
    },
  },
  focus: {
    yellow: { value: tokens.Color.Primitive.Yellow[700].value },
    blue: { value: tokens.Color.Primitive.LightBlue[700].value },
  },
};

export default colors;
