import type { PropsWithChildren } from "react";
import type { Metadata } from "next";
import BaseLayout from "@/components/layout/base";
import { notoSansJp, notoSansMono } from "@/styles/fonts";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ja">
      <body className={`${notoSansJp.variable} ${notoSansMono.variable}`}>
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  );
}
